### PR TITLE
Hipercard - A Brazilian Credit Card

### PR DESCRIPTION
**Pull request by tinogomes**

### CODE REVIEW

**Comment by muffinresearch** [comment]
Thanks for the PR. 

Any chance you could update it so the Hipercard mark is used with a card shape for the `flat`, `mono` and `outline` versions for consistency with the other icons?

For reference here's the existing set http://muffinresear.ch/payment-icons/ so you can see how they look together.

**Comment by tinogomes** [comment]
I will do that. My mistake!

**Comment by muffinresearch** [comment]
> I will do that. My mistake!

No worries at all, I appreciate the contribution!

**Comment by tinogomes** [comment]
@muffinresearch fixed `outline`, `flat`, and `mono` images.

**Comment by muffinresearch** [comment]
@tinogomes looks good good to me. For the flat version, is the grey background + text  `rgba(238, 238, 238)` colour part of the hipercard colour scheme? If that's not a colour dictated by the logo I wonder if nothing else the text should be `#fff`.

**Comment by tinogomes** [comment]
@muffinresearch You are right! DONE!

**Comment by muffinresearch** [comment]
@tinogomes - Muito obrigado! I'll merge this, generate the minified files and cut a release shortly!

**Pull request merged**
