### PR TITLE
added Elo Debit Card

### PR DESCRIPTION
**Pull request by SolidLink**
Added Elo card. Elo is a major Brazilian debit card.

### CODE REVIEW

**Comment by muffinresearch** [comment]
@SolidLink thanks for the addition - and apologies for taking a while to get to this - could you limit the patch to just the new SVG - it'll make it easier to review and then I'll generate everything else as part of a new release once that's landed.

**Comment by SolidLink** [comment]
@muffinresearch Sorry for the delay. I reverted the build and just added the SVG files.

**Comment by muffinresearch** [comment]
@SolidLink perfect - thanks! I'll merge this and cut a new release.

**Comment by muffinresearch** [comment]
@SolidLink your additions are in the 0.0.13 release.

**Pull request merged**
