### PR TITLE
Add new mastercard payment logo

### PR DESCRIPTION
**Pull request by wolfadex**
Addresses #6, the file is copied from https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html and then the white space around the original file was removed.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Hi, thanks for the PR. To fix #6 this would need to add a new mastercard logo for all the various styles and follow the existing look and feel for each style see http://muffinresear.ch/payment-icons/ for the examples of each type.

Note the rounded corners etc. If you're up for doing you can add further icons via further commits to this PR. 

I appreciate that's a lot to ask so if you'd rather leave it for now that's totally OK too.

**Comment by wolfadex** [comment]
I'd definitely be up to it.

I'm curious as to why the rounded corners though. Shouldn't it match what the card company designates as their design? Or should there be 2 variations, 1 to match the existing design and 1 set that matches what the card companies designate as their design?

**Comment by muffinresearch** [comment]
> I'm curious as to why the rounded corners though. Shouldn't it match what the card company designates as their design? Or should there be 2 variations, 1 to match the existing design and 1 set that matches what the card companies designate as their design?

The rounded corners is just the design I used here to provide a card-like shape for each logo than anything. It's not really anything new - card-shape icons are quite common for this sort of thing. 

The original use-case was to show a logo when a particular card provider is identified like so:

card_form

And a result a consistent look was needed for each icon as opposed to using a lot of different acceptance marks since they would vary.

**Comment by wolfadex** [comment]
Cool, I can totally update it then to be rounded and update the other logos too.

Do you mind if I update the Visa and Discover logos to match their current design too? The current Visa logo, according to http://www.visa.ca/merchant/resources/index.jsp, has a yellow and blue bar, The Discover logo has a white background and black border.

**Comment by muffinresearch** [comment]
> Do you mind if I update the Visa and Discover logos to match their current design too? The current Visa logo, according to http://www.visa.ca/merchant/resources/index.jsp, has a yellow and blue bar, The Discover logo has a white background and black border.

I would say don't make it part of this PR, it would be better to file new issues stating the case for why the change is needed and provide links to supporting resources. From a quick look the linked Visa logo looks like POS (point of sale) logo, I'm not sure we need to update these to look like that unless the bars are now part of the standard visa logo.

**Comment by muffinresearch** [comment]
Closing this for now.

**Pull request closed without merging**
