### PR TITLE
Adding the paypal icon and new group of icons

### PR DESCRIPTION
**Pull request by marcos-paiva**
# Content

This pull request adds a few extras that may be interesting for more general projects.

**In my case**, had a paypal icon. It was generated from *FontAwesome* vector.

Another feature that was needed to get the icons outside the rectangle with rounded edges.

To resolve this, I created a new group of icons called "single". In it are the logos in its pure form.

### CODE REVIEW

**Comment by muffinresearch** [comment]
Looks good - thanks for making this!

The paypal vector has some issues as it looks to have some lines that aren't straight (coming out of the curves (see the bottom of the P) if you compare it to the paypal logos available here: https://www.paypal-media.com/au/logos

See:

payment-icons_paypal_svg_at_678e79a1ade03a58c879229f95cf03c6ca0670a0_ _marcos-paiva_payment-icons

Also see the 'a' are now different. Would you mind updating to use the official Paypal logo as the source. Let me know if you need an eps converted. Also it looks like the colours may have changed very slightly assuming that's not an optical illusion.

Would you mind you changing the dir 'single' to 'logo' - that feels a better fit for what you've done.

Thanks again - if you can make those revisions I'll be happy to merge.

**Comment by marcos-paiva** [comment]
Hey, really!

I was betrayed by my eyes, but now it's all right with paypal :grin:

On the folder name, I think **"single"** is better than **"logo."** See that we are showing logos all the time, so call the folder "logo" does not seem to represent something semantically more correct (of course, if we are always placing the logo in a context - eg mono, flat, outline. );

You think we can continue?

Thank you :bowtie:

**Comment by muffinresearch** [comment]
@marcos-paiva cool - this is good to merge - thanks! I'll possibly change the dir to something else later e.g. brandmarks but this is fine for now.

**Comment by muffinresearch** [comment]
Btw I'll do a release tomorrow as I suspect I'll need to update the npm api key since all that changed.

**Pull request merged**
